- name: Update package cache - apt
  become: yes
  apt:
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Update package cache - yum
  become: yes
  yum:
    update_cache: yes
  when: ansible_pkg_mgr == 'yum'

- name: Update package cache - dnf
  become: yes
  dnf:
    update_cache: yes
  when: ansible_pkg_mgr == 'dnf'

- name: Update package cache - apk
  become: yes
  community.general.apk:
    update_cache: yes
  when: ansible_pkg_mgr == 'apk'
