- name: Update package cache
  become: yes
  package:
    update_cache: yes
  when: ansible_pkg_mgr != 'apk'

- name: Update package cache - apk
  become: yes
  community.general.apk:
    update_cache: yes
  when: ansible_pkg_mgr == 'apk'
